const ACTION_TYPES = {
    CATEGORY: "CATEGORY",
    CONTENT_DETAILS: "CONTENT_DETAILS",
    SHOW_CONTENT_DETAILS: "SHOW_CONTENT_DETAILS",
    ADD_FAVORITE: "ADD_FAVORITE"
}

export default ACTION_TYPES
